---
title: "О проекте Regina Lab"
description: |
  Краткая информация о проекте.  
output:
  distill::distill_article:
    self_contained: false
    code_folding: true
    highlight: kate
    highlight_downlit: true
    toc: false
    toc_depth: 3
    toc_float: true
---

### Цели проекта{#purpose}

1. Учиться и практиковать прикладной анализ данных. 

2. Делиться наработками и интересными данными. 

3. Повышать популярность языка R.


### За что стоим

* Российская Федерация

* открытые лицензии

* примат права

### Как получить данные?{#data}

Мы будем публиковать собранные нами данные в тех случаях, когда это не нарушает права третьих лиц. К сожалению, в России даже официальные данные чаще всего публикуются без указания условий дальнейшего использования, поэтому очень часто вместо данных мы будем оставлять ссылку на источник. Если вас интересуют данные из наших публикаций для собственного исследовательского проекта, напишите нам на [regina.obninsk@gmail.com](mailto:regina.obninsk@gmail.com).

### Хочу научиться так же. Вы проводите мастер-классы?{#teach} 

По нашему убеждению data science -- это современный Шаолинь, он требует внутренней дисциплины и закалки. Мы франшизы не "отбиваем" и на оболванивании школоты мигающими диодами не зарабатываем. Поэтому, всё по-серьёзному.

Если вы уже знакомы с R, мы всегда готовы помочь советом и открыты к обмену опытом. Если вы энтузиаст без опыты, порекомендуем книги и курсы.

### Можно заказать сбор данных? {#assist}

Мы принципиально не собираем данные для перепродажи, поэтому у нас нет каталога с ценами. Если у вас есть задача, связанная со сбором или обработкой данных, мы готовы её рассмотреть. Если её выполнение потребует существенных усилий, можем предложить оплатить работу.

### А давайте вместе сделаем проект? {#together}

Если проект интересен и может сделать мир лучше, давайте сделаем.

### В ваших материалах есть ошибки {#feedback}

Мы готовы признавать свои ошибки или дополнить наши исследования дополнительными материалами. Пишите нам на [regina.obninsk@gmail.com](mailto:regina.obninsk@gmail.com) и мы ответим в течение 48 часов. 

Если вы пришлете неоспоримое доказательство нашей неправоты, мы обновим пост и напишем об этом новость в ТГ-канале. 

Если считаете, что в исследовании не упомянуты важные сведения и пришлете нам дополнительную информацию, мы рассмотрим данные и постараемся добавить их к публикации. 

### Могу заказать вам решить задачки по R? {#noway}

Ответ отрицательный.

### Кто вы такие? Как вас зовут? {#who}

Популяризация data science не требует личной известности. Мы - это наши проекты, наши принципы, наш вклад в развитие общественных, научных и прикладных инициатив. Мы живем и работаем в России.

### Кто за вами стоит, кто вам платит? {#coi}

Никто. Мы принципиально не занимаемся политикой, чёрным PR или отработкой заказов.

### Кредо{#credo}

В чем нет услады, в том и пользы нет. Что вам по нраву, то и изучайте. 

### Использование{#using}

Если не указано иное, то статьи целиком и составляющие их тексты, иллюстрации и данные могут использоваться на условиях публичной лицензии [Creative Commons CC BY 4.0 Deed Attribution 4.0 International](https://creativecommons.org/licenses/by/4.0/deed.ru){target="_blank"}.

### Политика обработки персональных данных

Сайт https://reginaobninsklab.github.io не собирает персональные данные посетителей.

### Отказ от ответственности {#warranty}

В соответствии с действующим законодательством Российской Федерации владелец Сайта https://reginaobninsklab.github.io отказывается от каких-либо заверений и гарантий, предоставление которых может иным образом подразумеваться, и отказывается от ответственности в отношении вышеуказанного Сайта, его содержимого и их использования.

Ни при каких обстоятельствах владелец Сайта не будет нести ответственности ни перед какой стороной за какой-либо прямой, непрямой, особый или иной косвенный ущерб в результате любого использования информации на этом Сайте или на любом другом сайте, на который имеется гиперссылка с нашего cайта, даже если он будет явно поставлен в известность о возможности такого ущерба.

Пользователь настоящим прочтением документа соглашается с тем, что все возможные споры будут разрешаться только по нормам российского гражданского права.

Пользователь соглашается с тем, что нормы и законы РФ о защите прав потребителей не могут быть применимы к использованию им Сайта, поскольку сайт не оказывает возмездных услуг.

Используя Сайт https://reginaobninsklab.github.io Вы выражаете свое согласие с разделом «Отказ от ответственности» и установленными владельцем Сайта Правилами и принимаете всю ответственность, которая может быть на вас возложена действующим российским законодательством РФ.

## Поделиться {.appendix}

<!-- AddToAny BEGIN -->
<div class="a2a_kit a2a_kit_size_32 a2a_default_style" data-a2a-icon-color="unset">
<a class="a2a_button_telegram"></a>
<a class="a2a_button_vk"></a>
<a class="a2a_button_odnoklassniki"></a>
<a class="a2a_button_email"></a>
<a class="a2a_button_livejournal"></a>
<a class="a2a_button_mastodon"></a>
<a class="a2a_button_x"></a>
<a class="a2a_button_wechat"></a>
<a class="a2a_button_whatsapp"></a>
<a class="a2a_button_facebook_messenger"></a>
<a class="a2a_button_viber"></a>
</div>
<script async src="https://static.addtoany.com/menu/page.js"></script>
<!-- AddToAny END -->
