---
title: "Данные проекта Regina Lab"
description: |
  В разделе приведены ссылки на данные, доступные в сети Интернет или собранные нами самостоятельно. Если считаете, что публикация данных нарушает ваши права или общественный порядок, уведомите нас посредством [regina.obninsk@gmail.com](mailto:regina.obninsk@gmail.com).
output:
  distill::distill_article:
    self_contained: false
    code_folding: true
    highlight: kate
    highlight_downlit: true
    toc: false
    toc_depth: 3
    toc_float: true
---

### Такси

> 1. Федеральный реестр (ФГИС Такси): https://sicmt.ru/fgis-taksi [web]
>
> 2. Региональный реестр: https://uatk.admoblkaluga.ru/page/reestr-razresheniy/ [XML]

Наши материалы ([#такси](https://reginaobninsklab.github.io/#category:%D1%82%D0%B0%D0%BA%D1%81%D0%B8){target="_blank"}):

- [Такси Калужской области (часть 1)](https://reginaobninsklab.github.io/posts/kaluga-taxi-part1/){target="_blank"}

- [Такси Калужской области (часть 2)](https://reginaobninsklab.github.io/posts/kaluga-taxi-part2/){target="_blank"}

- [Такси Калужской области (часть 3)](https://reginaobninsklab.github.io/posts/kaluga-taxi-part3/){target="_blank"}

### Школы

> 1. Портал ГИА (ЕГЭ) Калужской области: http://ege.kaluga.ru [🙈]
>
> 2. Всероссийская олимпиада школьников Калужской области: http://vsosh-kaluga.ru/ [🙈]

Наши материалы ([#школы](https://reginaobninsklab.github.io/#category:%D1%88%D0%BA%D0%BE%D0%BB%D1%8B){target="_blank"}):

- [Открытый рейтинг школ Калужской области (часть 1)](https://reginaobninsklab.github.io/posts/kaluga-schools-rank-part1/){target="_blank"}

- [Какие предметы ЕГЭ выбирают девушки и юноши Калужской области?](https://reginaobninsklab.github.io/posts/kaluga-gender-gia/){target="_blank"}

### ДТП

> 1. Статистика ДТП https://dtp-stat.ru/?center=55.09723963686176%3A36.60650628383811 [geojson]
>
> 2. Статистика ДТП 2015-2024 https://tochno.st/datasets/traffic_accidents [csv, xlsx]

### Закупки 

> 1. Портал "Малые закупки" Калужской области: https://mimz.admoblkaluga.ru/Menu/Page/1 [XLSX]
>
> 2. ГосЗакупки: https://zakupki.gov.ru/epz/main/public/home.html

### Трудозатраты выпускников

> 1. Трудоустройство и зарплаты выпускников по направлениям подготовки 2019-2023: https://tochno.st/datasets/graduates_fields [csv, xlsx]
>
> 2. Трудоустройство и зарплаты выпускников по образовательным организациям 2019-2023: https://tochno.st/datasets/graduates_university [csv, xlsx]

### Климат

> Open Meteo https://open-meteo.com/en/docs/historical-weather-api [API]
>
> Архив метеорологических данных с 2008 по 2023 г. Институт экспериментальной метеорологии ФГБУ НПО "Тайфун" http://www.vmm310.ru/ru/daily_flow.asp [txt]. Скрипт R для чтения [R](https://reginaobninsklab.github.io/posts/obninsk-climate-part3-sources/scripts/typhoon_vmm_data.R){target="_blank"} 

Наши материалы ([#климат](https://reginaobninsklab.github.io/index.html#category:%D0%BA%D0%BB%D0%B8%D0%BC%D0%B0%D1%82)):

- [Глобальное потепление и сентябрьская погода в г. Обнинск (Часть 1. Температура)](https://reginaobninsklab.github.io/posts/obninsk-climate-part1-temp/){target="_blank"}

- [Глобальное потепление и сентябрьская погода в г. Обнинск (Часть 2. Осадки)](https://reginaobninsklab.github.io/posts/obninsk-climate-part2-rains/){target="_blank"}

- [Надёжность сведений о погоде в г.Обнинск (Часть 3. Источники данных)](https://reginaobninsklab.github.io/posts/obninsk-climate-part3-sources/){target="_blank"}

### Государственный надзор

> 1. ФГИС "Единый реестр проверок" (Прокуратура РФ): https://proverki.gov.ru/portal/public-open-data [XML]
>
> 3. Реестр дисквалифицированных лиц (Минюст России): https://www.nalog.gov.ru/opendata/7707329152-registerdisqualified/ [csv]
>
> 4. Единый реестр субъектов малого и среднего предпринимательства (ФНС): https://www.nalog.gov.ru/opendata/7707329152-rsmp/ [csv]
>
> 5. Реестр лиц, уволенных в связи с утратой доверия: https://gossluzhba.gov.ru/reestr [xls]
>
> 6. Реестр иностранных агентов (Минюст России): https://minjust.gov.ru/ru/activity/directions/998/ [pdf]
>
> 7. Перечень иностранных и международных неправительственных организаций, деятельность которых признана нежелательной на территории Российской Федерации: https://minjust.gov.ru/ru/documents/7756/ [web, docx]
>
> 8. Реестр некоммерческих организаций (Минюст России): https://minjust.gov.ru/ru/pages/reestr-nekommercheskih-organizacij/ [xls]
>
> 9. Сведения из государственного сводного реестра выданных, приостановленных и аннулированных лицензий на производство и оборот этилового спирта, алкогольной и спиртосодержащей продукции: https://fsrar.gov.ru/licens/reestr [web]
>
> 10. Реестр лицензий на осуществление деятельности по организации и проведению азартных игр в букмекерских конторах или тотализаторах: https://www.nalog.gov.ru/opendata/7707329152-reestrlicbookmaker/ [csv]

### Общественный надзор

> 1. ГосЗатраты: https://clearspending.ru/ [API]
>
> 2. Картелескоп: https://tenderscope.org/cartels.php?region=40 
>
> 3. Декларатор: https://declarator.org/ [API]
>
> 4. Выборотека: https://vyboroteka.org

### Обнинск

> 1. Открытые данные г.Обнинск: http://www.admobninsk.ru/opendata/
>
> 2. Многоквартирные дома в Обнинске: https://dom.mingkh.ru/kaluzhskaya-oblast/obninsk/houses [web]
>
> 3. Аварийные дома в Обнинске: https://dom.mingkh.ru/avarijnye/kaluzhskaya-oblast/obninsk/ [web]

### СМИ

Наши материалы ([#сми](https://reginaobninsklab.github.io/#category:%D1%81%D0%BC%D0%B8){target="_blank"})

### Telegram

Наши материалы ([#телеграм](https://reginaobninsklab.github.io/#category:%D1%82%D0%B5%D0%BB%D0%B5%D0%B3%D1%80%D0%B0%D0%BC){target="_blank"})


## Использование {.appendix}

Если не указано иное, то статья целиком и составляющие её текст, иллюстрации и данные, могут использоваться на условиях бесплатной неисключительной лицензии [Creative Commons CC BY 4.0 Deed Attribution 4.0 International](https://creativecommons.org/licenses/by/4.0/deed.ru){target="_blank"}.

## Поделиться {.appendix}

<!-- AddToAny BEGIN -->
<div class="a2a_kit a2a_kit_size_32 a2a_default_style" data-a2a-icon-color="unset">
<a class="a2a_button_telegram"></a>
<a class="a2a_button_vk"></a>
<a class="a2a_button_odnoklassniki"></a>
<a class="a2a_button_email"></a>
<a class="a2a_button_livejournal"></a>
<a class="a2a_button_mastodon"></a>
<a class="a2a_button_x"></a>
<a class="a2a_button_wechat"></a>
<a class="a2a_button_whatsapp"></a>
<a class="a2a_button_facebook_messenger"></a>
<a class="a2a_button_viber"></a>
</div>
<script async src="https://static.addtoany.com/menu/page.js"></script>
<!-- AddToAny END -->
